# Quick validation before commiting changes:
# prompt$ circleci config validate .circleci/config.yml
# Installing on MacOS:
# prompt$ brew install circleci

version: 2.1

jobs:
  build_deploy:
    executor: deployer
    steps:
      - build_deploy:
          region: eu-west-1
          client_bucket: s3://verbit-live-demo-internal

commands:
  build_deploy:
    parameters:
      region:
        description: Deploy region
        type: string
        default: eu-west-1
      client_bucket:
        description: Deploy bucket for client static assets
        type: string
    steps:
      - run:
          name: build assets and deploy to s3 bucket
          command: |
            apt update
            apt install -y --no-install-recommends awscli
            npm run build
            aws s3 sync ./public << parameters.client_bucket >> --delete

executors:
  deployer:
    docker:
      - image: node:12.20-buster

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - main
